stages:
    - test
    - build

test:
    image: node:17-alpine
    stage: test
    tags: 
        - test
    script:
        - npm install
        - npm test

build:
    image: node:17-alpine
    stage: build
    tags:
        - build
    script:
        - sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        - sudo dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
        - sudo systemctl --now enable docker
        - docker compose up

