stages:
    - test
    - build

test:
    image: node:17-alpine
    stage: test
    tags: 
        - test
    script:
        - npm install
        - npm test

build:
    image: rockylinux:9.0.20220720-minimal
    stage: build
    tags:
        - build
    script:
        -  dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        -  dnf -y install docker-ce docker-ce-cli containerd.io docker-compose-plugin
        -  systemctl --now enable docker
        - docker compose up


